/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;
import java.util.StringJoiner;

public class App {

    public static void main(String[] args) {

        try {
            // Create a new Gson object
            Gson gson = new Gson();
            

            // Read the recentquotes.json file
            Scanner scanner = new Scanner(new File("src/main/resources/recentquotes.json"));


            StringJoiner oneliner = new StringJoiner(" ");

            while (scanner.hasNextLine()) {

                oneliner.add(scanner.nextLine());
            }

            Quote[] quoteArray = gson.fromJson(oneliner.toString(), Quote[].class);

            Random rand = new Random();
            int randInt = rand.nextInt(quoteArray.length);

            System.out.println("Here is your quote: \n " + quoteArray[randInt]);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
