/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;
import java.util.StringJoiner;

public class App {

    public static void main(String[] args) {
        System.out.println(getRandomQuote("src/main/resources/recentquotes.json"));
    }
    public static int getRandomInt(int arrLength) {
        Random rand = new Random();
        int randInt = rand.nextInt(arrLength - 1);
        return randInt;
    }
    public static String getRandomQuote(String filePath) {
        try {

            FileReader file = new FileReader(filePath);

            Gson gson = new Gson();

            Quote[] quoteArray = gson.fromJson(file, Quote[].class);


//            System.out.println("Here is your quote: \n " + quoteArray[randInt]);
            int randInt = getRandomInt(quoteArray.length);

            String randomQ = quoteArray[randInt].toString();

            return randomQ;

        } catch (IOException e) {
            e.printStackTrace();
            return "Error: Your filename is incorrect.";
        }
    }
}
